//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartForm.Domain
{
    using System;
    using System.Collections.Generic;
    using System.Reflection;

    public partial class FormTemplateFieldDefinition
    {
       


        public int FormTemplateFieldDefinitionId { get; set; }
        public string GUID { get; set; }
        public string FieldName { get; set; }
        public int DataTypeId { get; set; }
        public string LabelFieldName { get; set; }
        public int FormTemplateId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModfied { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string ControlType { get; set; }
        public int SortOrder { get; set; }
    
        public virtual DataType DataType { get; set; }
        public virtual FormTemplate FormTemplate { get; set; }
    }
}
