//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartForm.Domain
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Reflection;

    public partial class FormData
    {


        public object this[string propertyName]
        {
            get
            {
                // probably faster without reflection:
                // like:  return Properties.Settings.Default.PropertyValues[propertyName] 
                // instead of the following
                Type myType = typeof(FormData);
                PropertyInfo myPropInfo = myType.GetProperty(propertyName);
                return myPropInfo.GetValue(this, null);
            }
            set
            {
                Type myType = typeof(FormData);
                PropertyInfo myPropInfo = myType.GetProperty(propertyName);
                myPropInfo.SetValue(this, value, null);

            }

        }



        public int FormDataId { get; set; }
        public string GUID { get; set; }
        public int FormId { get; set; }
        public string FlexField1 { get; set; }
        public string FlexField2 { get; set; }
        public string FlexField3 { get; set; }
        public string FlexField4 { get; set; }
        public string FlexField5 { get; set; }
        public string FlexField6 { get; set; }
        public string FlexField7 { get; set; }
        public string FlexField8 { get; set; }
        public string FlexField9 { get; set; }
        public string FlexField10 { get; set; }
        public string FlexField11 { get; set; }
        public string FlexField12 { get; set; }
        public string FlexField13 { get; set; }
        public string FlexField14 { get; set; }
        public string FlexField15 { get; set; }
        public string FlexField16 { get; set; }
        public string FlexField17 { get; set; }
        public string FlexField18 { get; set; }
        public string FlexField19 { get; set; }
        public string FlexField20 { get; set; }
        public string FlexField21 { get; set; }
        public string FlexField22 { get; set; }
        public string FlexField23 { get; set; }
        public string FlexField24 { get; set; }
        public string FlexField25 { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModfied { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        [JsonIgnore]    
        public virtual Form Form { get; set; }
    }
}
