//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartForm.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form()
        {
            this.FormDatas = new HashSet<FormData>();
        }
    
        public int FormId { get; set; }
        public string GUID { get; set; }
        public int UserId { get; set; }
        public int FormTemplateId { get; set; }
        public int FormStatus { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModfied { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormData> FormDatas { get; set; }
        public virtual FormStatu FormStatu { get; set; }
        public virtual FormTemplate FormTemplate { get; set; }
        public virtual User User { get; set; }
    }
}
